### ISSUE TITLE
Minification Error: not annotated

### ISSUE THREAD

**Issue by ValentinFunk** [pbastowski/angular-babel#2]
When building an app like this: https://github.com/Kamshak/minification (running with --production)
The following isn't annotated:

``` js
'use strict';

import angular from 'angular';
angular.module('ps2StoreApp')
.config(function($httpProvider) {
  $httpProvider.useLegacyPromiseExtensions(true);
});
```

results in

```
f466ddc….js?meteor_js_resource=true:25 Uncaught Error: [$injector:modulerr] Failed to instantiate module ps2StoreApp due to:
Error: [$injector:unpr] Unknown provider: e
http://errors.angularjs.org/1.5.5/$injector/unpr?p0=e
    at http://localhost:8080/f466ddcf7552fb1b32a54e445ed75b03084d472a.js?meteor_js_resource=true:25:2617
    at http://localhost:8080/f466ddcf7552fb1b32a54e445ed75b03084d472a.js?meteor_js_resource=true:25:23552
    at r (http://localhost:8080/f466ddcf7552fb1b32a54e445ed75b03084d472a.js?meteor_js_resource=true:25:22480)
    at i (http://localhost:8080/f466ddcf7552fb1b32a54e445ed75b03084d472a.js?meteor_js_resource=true:25:22780)
    at Object.a [as invoke] (http://localhost:8080/f466ddcf7552fb1b32a54e445ed75b03084d472a.js?meteor_js_resource=true:25:22980)
    at r (http://localhost:8080/f466ddcf7552fb1b32a54e445ed75b03084d472a.js?meteor_js_resource=true:25:21868)
    at http://localhost:8080/f466ddcf7552fb1b32a54e445ed75b03084d472a.js?meteor_js_resource=true:25:21992
    at r (http://localhost:8080/f466ddcf7552fb1b32a54e445ed75b03084d472a.js?meteor_js_resource=true:25:3065)
    at h (http://localhost:8080/f466ddcf7552fb1b32a54e445ed75b03084d472a.js?meteor_js_resource=true:25:21769)
    at rt (http://localhost:8080/f466ddcf7552fb1b32a54e445ed75b03084d472a.js?meteor_js_resource=true:25:23724)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=ps2StoreApp&p1=Erro…52fb1b32a54e445ed75b03084d472a.js%3Fmeteor_js_resource%3Dtrue%3A25%3A23724)
```

When removing 

```
'use strict';

import angular from 'angular'; 
```

it starts to work again. What is the cause of this? Seems very strange to me

**Comment by pbastowski** [comment]
@Kamshak 
I just tried your example code and it works just fine for me when running with the "--production" Meteor flag, but only after making one change, see below:

Use this format

``` js
import 'angular';
```

instead of 

``` js
import angular from 'angular';
```

**Comment by ValentinFunk** [comment]
That does work! Any idea why?

I have also update the repo with another error that i ran into when using the ui-router. I'm not sure if this is caused by using the es6 syntax or something else, would you have any idea why it happens? 

```
Swallowed exception during synchronous hook handler: Error: [$injector:unpr] Unknown provider: eProvider <- e
http://errors.angularjs.org/1.5.5/$injector/unpr?p0=eProvider%20%3C-%20e
```

**Comment by ValentinFunk** [comment]
I think this is caused by ngAnnotate, had a similar error while using ng-annotate with gulp

**Comment by pbastowski** [comment]
@Kamshak 
I have only just now noticed that you posted this issue in the `angular-babel` repo, instead of my [`anular-meteor-babel`](https://github.com/pbastowski/angular-meteor-babel) repo. This repo ( `angular-babel` ) is actually deprecated. I will mark it as deprecated, so no one else posts here by mistake. Sorry for the confusion.

Now, the error message you got, above, simply means that something in your code was not annotated. This is quite possible, as ng-annotate only knows of specific angular patterns. If you use something that it does not recognise then it won't annotate it. In such a case you can either annotate the function manually or force ng-annotate to annotate by using the "ngInject" string literal, as shown below

``` js
function foo($scope) { "ngInject"; ... } 
```

For more info have a look [here](https://www.npmjs.com/package/ng-annotate)

**Comment by ValentinFunk** [comment]
Thanks
